### ISSUE TITLE
Can't provide your own Promise polyfill

### ISSUE THREAD

**Issue by 0xR** [terinjokes/promisescript#4]
This depends on es6-promise. If you already have loaded a promise polyfill or the browser already supports them es6-promise will still be loaded.

**Comment by terinjokes** [comment]
Ok, will fix.

**Comment by terinjokes** [comment]
I plan on changing this to use `anypromise`, which lets people override the Promise implementation if they want, and use the native (or polyfilled) Promise otherwise.
